Repository LuxoriaSoft/Luxoria, pull requests merged in 2025-07, with the labels that each got.

#332 Feat/lda/luxexport
  Modules/LuxExport/LuxExport/Components/Export.xaml
  Modules/LuxExport/LuxExport/Components/Export.xaml.cs
  Modules/LuxExport/LuxExport/Components/ExportProgressWindow.xaml.cs
  Modules/LuxExport/LuxExport/Logic/Exporters.cs
  Modules/LuxStudio/LuxStudio/LuxStudio.cs
Labels: Feature

#334 merge: Develop to Main
  CHANGELOG.md
  Luxoria.App/Luxoria.Modules/Models/Events/RequestTokenEvent.cs
  Luxoria.App/Luxoria.Modules/Models/Events/UpdateUpdatedAssetEvent.cs
  Luxoria.App/Luxoria.Modules/Models/Events/WebCollectionSelectedEvent.cs
  Modules/LuxEditor/LuxEditor/Components/Infos.xaml
  Modules/LuxEditor/LuxEditor/Components/Infos.xaml.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.cs
  Modules/LuxEditor/LuxEditor/Models/EditableImage.cs
  Modules/LuxEditor/LuxEditor/Properties/launchSettings.json
  Modules/LuxExport/LuxExport/Components/Export.xaml
  Modules/LuxExport/LuxExport/Components/Export.xaml.cs
  Modules/LuxExport/LuxExport/Components/ExportProgressWindow.xaml.cs
  Modules/LuxExport/LuxExport/Logic/Exporters.cs
  Modules/LuxImport/LuxImport/LuxImport.cs
  Modules/LuxStudio/LuxStudio.COM/Services/CollectionService.cs
  Modules/LuxStudio/LuxStudio/LuxStudio.cs
  gonogo-review/BTP_Scenarios/Scenario 5.docx
  gonogo-review/BTP_Scenarios/Scenario 5.pdf
  gonogo-review/Roadmap PG5.docx
  gonogo-review/Roadmap PG5.pdf
Labels: Feature

#338 Merge Develop to Main
  CHANGELOG.md
  Luxoria.App/Luxoria.Modules/Models/LuxAsset.cs
  Modules/LuxEditor/LuxEditor/Components/CollectionExplorer.xaml
  Modules/LuxEditor/LuxEditor/Components/CollectionExplorer.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/FilterBar.xaml
  Modules/LuxEditor/LuxEditor/Components/FilterBar.xaml.cs
  Modules/LuxEditor/LuxEditor/Logic/LuxFilterManager.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.csproj
  Modules/LuxEditor/LuxEditor/LuxEditor.csproj.user
  Modules/LuxEditor/LuxEditor/Models/EditableImage.cs
  Modules/LuxExport/LuxExport/Components/Export.xaml.cs
  Modules/LuxExport/LuxExport/LuxExport.cs
  Modules/LuxFilter/LuxFilter/Services/FilterService.cs
Labels: Bug

#343 fix: Fix/luxstudio/luxmod
  Modules/LuxStudio/luxmod.json
Labels: Feature

#344 fix: Develop to Main
  CHANGELOG.md
  Modules/LuxStudio/luxmod.json
Labels: released on @develop
