Repository LuxoriaSoft/Luxoria, pull requests merged in 2025-06, with the labels that each got.

#251 feat: Bring a complete Filter workflow from pictures selection to communication to LuxEditor
  Luxoria.App/Luxoria.Modules/Models/Events/FilterAlgorithmsLoadedEvent.cs
  Luxoria.App/Luxoria.Modules/Models/FilterData.cs
  Luxoria.App/Luxoria.Modules/Models/LuxAsset.cs
  Modules/LuxEditor/LuxEditor/Components/CollectionExplorer.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/EditorSeparator.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/EditorSlider.cs
  Modules/LuxEditor/LuxEditor/EditorUI/EditorPanelManager.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Models/EditorStyle.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.cs
  Modules/LuxEditor/LuxEditor/Models/EditableImage.cs
  Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPAlgo.cs
  Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPModel/negative.txt
  Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPModel/positive.txt
  Modules/LuxFilter/LuxFilter.Algorithms/LuxFilter.Algorithms.csproj
  Modules/LuxFilter/LuxFilter.TestMain/Program.cs
  Modules/LuxFilter/LuxFilter.Tests/PipelineServiceTests.cs
  Modules/LuxFilter/LuxFilter/Components/AssetViewer.xaml
  Modules/LuxFilter/LuxFilter/Components/AssetViewer.xaml.cs
  Modules/LuxFilter/LuxFilter/Components/CollectionExplorer.xaml
  Modules/LuxFilter/LuxFilter/Components/CollectionExplorer.xaml.cs
  Modules/LuxFilter/LuxFilter/Components/FilterExplorer.xaml
  Modules/LuxFilter/LuxFilter/Components/FilterExplorer.xaml.cs
  Modules/LuxFilter/LuxFilter/Components/FilterToolBox.xaml
  Modules/LuxFilter/LuxFilter/Components/FilterToolBox.xaml.cs
  Modules/LuxFilter/LuxFilter/Components/FlagsComponent.xaml
  Modules/LuxFilter/LuxFilter/Components/FlagsComponent.xaml.cs
  Modules/LuxFilter/LuxFilter/Components/RatingComponent.xaml
  Modules/LuxFilter/LuxFilter/Components/RatingComponent.xaml.cs
  Modules/LuxFilter/LuxFilter/Components/ScoreViewer.xaml
  Modules/LuxFilter/LuxFilter/Components/ScoreViewer.xaml.cs
  Modules/LuxFilter/LuxFilter/Components/ToolBox.xaml
  Modules/LuxFilter/LuxFilter/Components/ToolBox.xaml.cs
  Modules/LuxFilter/LuxFilter/Interfaces/IPipelineService.cs
  Modules/LuxFilter/LuxFilter/LuxFilter.cs
  Modules/LuxFilter/LuxFilter/LuxFilter.csproj
  Modules/LuxFilter/LuxFilter/LuxFilter.csproj.user
  Modules/LuxFilter/LuxFilter/Models/FilterItem.cs
  Modules/LuxFilter/LuxFilter/Services/FilterService.cs
  Modules/LuxFilter/LuxFilter/Services/PipelineService.cs
  Modules/LuxFilter/LuxFilter/Views/FilterView.xaml
  Modules/LuxFilter/LuxFilter/Views/FilterView.xaml.cs
  Modules/LuxFilter/LuxFilter/Views/MainFilterView.xaml.cs
  Modules/LuxFilter/LuxFilter/Views/StatusView.xaml
  Modules/LuxFilter/LuxFilter/Views/StatusView.xaml.cs
Labels: Bug, Documentation, Feature

#253 fix: WhoAmI method returns User method without sensitive informations
  LuxStudio/LuxAPI/LuxAPI/Controllers/AuthController.cs
Labels: Bug

#254 hotfix: Fix generation of JWT Token on SSOController
  LuxStudio/LuxAPI/LuxAPI/Controllers/AuthController.cs
  LuxStudio/LuxAPI/LuxAPI/Controllers/SSOController.cs
Labels: Bug

#255 refactor: Creation of JWT Service to manage JWT Creation
  LuxStudio/LuxAPI/LuxAPI/Controllers/AuthController.cs
  LuxStudio/LuxAPI/LuxAPI/Controllers/SSOController.cs
  LuxStudio/LuxAPI/LuxAPI/Program.cs
  LuxStudio/LuxAPI/LuxAPI/Services/Interfaces/IJWTService.cs
  LuxStudio/LuxAPI/LuxAPI/Services/JWTService.cs
Labels: Bug, Documentation

#265 feat: Integrate LuxMarketPlace Manager
  .github/workflows/marketplace-upload.yml
  tools/luxmktplacemgr/.gitignore
  tools/luxmktplacemgr/README.md
  tools/luxmktplacemgr/pyproject.toml
  tools/luxmktplacemgr/src/luxmktplacemgr/__init__.py
  tools/luxmktplacemgr/src/luxmktplacemgr/main.py
  tools/luxmktplacemgr/src/uploadmgr/__init__.py
  tools/luxmktplacemgr/src/uploadmgr/main.py
  tools/luxmktplacemgr/tests/__init__.py
Labels: released on @develop

#278 feat: Integration of LuxEditor @2.0.1
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml.cs
  Modules/LuxEditor/LuxEditor/Logic/LayerManager.cs
  Modules/LuxEditor/LuxEditor/Models/Layer.cs
Labels: Bug

#279 refactor: LuxMKTMGR/building part & fix production-ready LuxStudio
  LuxStudio/LuxAPI/LuxAPI/Controllers/CollectionController.cs
  LuxStudio/LuxAPI/LuxAPI/Program.cs
  LuxStudio/LuxAPI/LuxAPI/Services/MinioService.cs
  LuxStudio/depl/base/deployment-minio.yaml
  LuxStudio/depl/base/minio-passwdgen.sh
  LuxStudio/depl/overlays/pluto/luxapi-secrets.sh
  LuxStudio/depl/overlays/pluto/patch-deployment-luxapi.yaml
  LuxStudio/portal/src/views/CollectionChat.vue
  LuxStudio/portal/src/views/CollectionDetail.vue
  tools/luxmktplacemgr/src/buildmgr/main.py
Labels: Bug, Feature

#288 feat: Create Marketplace Manager + ModuleInstaller
  Luxoria.App/Luxoria.App/App.xaml.cs
  Luxoria.App/Luxoria.App/Components/MainMenuBarComponent.xaml
  Luxoria.App/Luxoria.App/Components/MainMenuBarComponent.xaml.cs
  Luxoria.App/Luxoria.App/Components/SplashScreen.xaml
  Luxoria.App/Luxoria.App/Components/SplashScreen.xaml.cs
  Luxoria.App/Luxoria.App/Dialogs/ImportationDialog.cs
  Luxoria.App/Luxoria.App/Dialogs/OpenCollectionDialog.cs
  Luxoria.App/Luxoria.App/Logics/Startup.cs
  Luxoria.App/Luxoria.App/Luxoria.App.csproj
  Luxoria.App/Luxoria.App/Luxoria.App.csproj.user
  Luxoria.App/Luxoria.App/MainWindow.xaml.cs
  Luxoria.App/Luxoria.App/SplashScreen.xaml.cs
  Luxoria.App/Luxoria.App/Views/ImportationControl.xaml
  Luxoria.App/Luxoria.App/Views/ImportationControl.xaml.cs
  Luxoria.App/Luxoria.App/Views/MarketplaceView.xaml
  Luxoria.App/Luxoria.App/Views/MarketplaceView.xaml.cs
  Luxoria.App/Luxoria.App/Views/ModuleManagerView.xaml
  Luxoria.App/Luxoria.App/Views/ModuleManagerView.xaml.cs
  Luxoria.App/Luxoria.App/Views/OpenCollectionControl.xaml
  Luxoria.App/Luxoria.App/Views/OpenCollectionControl.xaml.cs
  Luxoria.App/Luxoria.Core/Helpers/TmpDirHelper.cs
  Luxoria.App/Luxoria.Core/IMarketplaceService.cs
  Luxoria.App/Luxoria.Core/Luxoria.Core.csproj
  Luxoria.App/Luxoria.Core/Models/LuxRelease.cs
  Luxoria.App/Luxoria.Core/Services/MarketplaceService.cs
  Luxoria.App/Luxoria.Core/Services/ModuleInstaller.cs
  Luxoria.App/Luxoria.GModules/Helpers/WindowHelper.cs
  Luxoria.App/Luxoria.Modules/Interfaces/IStorageAPI.cs
  Luxoria.App/Luxoria.Modules/Luxoria.Modules.csproj
  Luxoria.App/Luxoria.Modules/VaultService.cs
Labels: Feature

#292 feat: Integration of LuxEditor @2.0.2
  Luxoria.App/Luxoria.App/MainWindow.xaml.cs
  Luxoria.App/Luxoria.GModules/Models/Events/OpenEvent.cs
  Luxoria.App/Luxoria.GModules/SmartButton.cs
  Luxoria.App/Luxoria.Modules/Models/Events/ExportRequestEvent.cs
  Luxoria.App/Luxoria.Modules/Models/Events/RequestLatestCollection.cs
  Modules/LuxEditor/LuxEditor/Components/CollectionExplorer.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/Infos.xaml
  Modules/LuxEditor/LuxEditor/Components/Infos.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/OptionNode.cs
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/PickSaveFileWindow.cs
  Modules/LuxEditor/LuxEditor/Components/PresetTemplateSelector.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ColorChannelCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/CurveBase.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/EditorSlider.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/LayersDetailsPanel.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ParametricCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/PointCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/ATool.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/Brush.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/LinearGradient.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/RadialGradient.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Groups/EditorToneCurveGroup.cs
  Modules/LuxEditor/LuxEditor/Logic/LayerManager.cs
  Modules/LuxEditor/LuxEditor/Logic/PresetManager.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.csproj
  Modules/LuxEditor/LuxEditor/Models/EditableImage.cs
  Modules/LuxEditor/LuxEditor/Models/ISerializableTool.cs
  Modules/LuxEditor/LuxEditor/Models/PresetsModels.cs
  Modules/LuxEditor/LuxEditor/Models/PresetsViewModel.cs
  Modules/LuxEditor/LuxEditor/Utils/Compare.cs
  Modules/LuxEditor/LuxEditor/Utils/WindowHandleHelper.cs
  Modules/LuxExport/LuxExport/Components/Export.xaml
  Modules/LuxExport/LuxExport/Components/Export.xaml.cs
  Modules/LuxExport/LuxExport/LuxExport.cs
Labels: Feature

#293 merge: Develop to Main
  .github/workflows/build-upload-lda.yml
  CHANGELOG.md
  Luxoria.App/Luxoria.App/MainWindow.xaml.cs
  Luxoria.App/Luxoria.GModules/Models/Events/OpenEvent.cs
  Luxoria.App/Luxoria.GModules/SmartButton.cs
  Luxoria.App/Luxoria.Modules/Models/Events/ExportRequestEvent.cs
  Luxoria.App/Luxoria.Modules/Models/Events/RequestLatestCollection.cs
  Modules/LuxEditor/LuxEditor/Components/CollectionExplorer.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/Infos.xaml
  Modules/LuxEditor/LuxEditor/Components/Infos.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/OptionNode.cs
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/PickSaveFileWindow.cs
  Modules/LuxEditor/LuxEditor/Components/PresetTemplateSelector.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ColorChannelCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/CurveBase.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/EditorSlider.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/LayersDetailsPanel.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ParametricCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/PointCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/ATool.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/Brush.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/LinearGradient.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/RadialGradient.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Groups/EditorToneCurveGroup.cs
  Modules/LuxEditor/LuxEditor/Logic/LayerManager.cs
  Modules/LuxEditor/LuxEditor/Logic/PresetManager.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.csproj
  Modules/LuxEditor/LuxEditor/Models/EditableImage.cs
  Modules/LuxEditor/LuxEditor/Models/ISerializableTool.cs
  Modules/LuxEditor/LuxEditor/Models/PresetsModels.cs
  Modules/LuxEditor/LuxEditor/Models/PresetsViewModel.cs
  Modules/LuxEditor/LuxEditor/Utils/Compare.cs
  Modules/LuxEditor/LuxEditor/Utils/WindowHandleHelper.cs
  Modules/LuxExport/LuxExport/Components/Export.xaml
  Modules/LuxExport/LuxExport/Components/Export.xaml.cs
  Modules/LuxExport/LuxExport/LuxExport.cs
Labels: Feature

#295 fix: Add async fetches for releases & Animation when a module has been installed.
  Luxoria.App/Luxoria.App/Components/MainMenuBarComponent.xaml.cs
  Luxoria.App/Luxoria.App/Views/MarketplaceView.xaml.cs
Labels: Bug

#296 feat: Integration of LuxEditor @2.0.4
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/CropController.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolSelectorBar.cs
  Modules/LuxEditor/LuxEditor/Logic/CropProcessor.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.cs
  Modules/LuxEditor/LuxEditor/Models/EditableImage.cs
Labels: Feature

#297 Feat: Integration of Luxexport-> Add watermarks
  Modules/LuxExport/LuxExport/Components/Export.xaml
  Modules/LuxExport/LuxExport/Components/Export.xaml.cs
  Modules/LuxExport/LuxExport/Components/ExportProgressWindow.xaml.cs
  Modules/LuxExport/LuxExport/Logic/ExportViewModel.cs
  Modules/LuxExport/LuxExport/Logic/WatermarkApplier.cs
  Modules/LuxExport/LuxExport/Logic/WatermarkService.cs
  Modules/LuxExport/LuxExport/Logic/WatermarkSettings.cs
  Modules/LuxExport/LuxExport/LuxExport.cs
Labels: Feature
