Repository LuxoriaSoft/Luxoria, pull requests merged in 2025-05, with the labels that each got.

#185 fix: Dependabot configuration file emplacement at .github
  .github/dependabot.yml
Labels: released on @develop

#209 ci: Standard Modules Release
  .github/workflows/build-upload-lda.yml
  .github/workflows/build-upload-standard-modules.yml
  .github/workflows/sonar-analysis.yml
  Luxoria.App/Luxoria.SDK/Luxoria.SDK.csproj
  Modules/LuxEditor/LuxEditor/LuxEditor.csproj
  Modules/LuxExport/LuxExport/LuxExport.csproj
  Modules/LuxFilter/LuxFilter.Algorithms/LuxFilter.Algorithms.csproj
  Modules/LuxFilter/LuxFilter.Benchmark/LuxFilter.Benchmark.csproj
  Modules/LuxFilter/LuxFilter.TestMain/LuxFilter.TestMain.csproj
  Modules/LuxFilter/LuxFilter.Tests/LuxFilter.Tests.csproj
  Modules/LuxFilter/LuxFilter/LuxFilter.csproj
  Modules/LuxImport/LuxImport.Tests/LuxImport.Tests.csproj
  Modules/LuxImport/LuxImport/LuxImport.cs
  Modules/LuxImport/LuxImport/LuxImport.csproj
  Modules/LuxImport/LuxImport/Views/ImportView.xaml.cs
Labels: Feature, dependencies

#218 Feat/lda/lux editor devbased
  Modules/LuxEditor/LuxEditor.sln
  Modules/LuxEditor/LuxEditor/Components/CollectionExplorer.xaml
  Modules/LuxEditor/LuxEditor/Components/CollectionExplorer.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml
  Modules/LuxEditor/LuxEditor/Components/Editor.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/Infos.xaml.cs
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/EditorSeparator.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/EditorSlider.cs
  Modules/LuxEditor/LuxEditor/EditorUI/EditorPanelManager.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Groups/EditorCategory.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Groups/EditorGroupExpander.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Interfaces/IEditorControl.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Interfaces/IEditorGroupItem.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Interfaces/IEditorStylable.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Models/EditorStyle.cs
  Modules/LuxEditor/LuxEditor/Logic/ImageManager.cs
  Modules/LuxEditor/LuxEditor/Logic/ImageProcessingManager.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.cs
  Modules/LuxEditor/LuxEditor/LuxEditor.csproj
  Modules/LuxEditor/LuxEditor/Models/EditableImage.cs
  Modules/LuxEditor/LuxEditor/Properties/launchSettings.json
  Modules/LuxEditor/LuxEditor/Utils/ExifHelper.cs
  assets/BaseCollection/Luxoria_logo.png
  assets/BaseCollection/NET Logo.png
Labels: Feature, .NET

#219 feat: Bring /desktop/config route
  LuxStudio/LuxAPI/LuxAPI/Controllers/DesktopController.cs
  LuxStudio/LuxAPI/LuxAPI/Migrations/20250513023628_InitChatMessages.Designer.cs
  LuxStudio/LuxAPI/LuxAPI/Migrations/20250513185152_AddAvatarToUser.cs
  LuxStudio/LuxAPI/LuxAPI/Migrations/20250523151545_InitialCreate.Designer.cs
  LuxStudio/LuxAPI/LuxAPI/Migrations/20250523151545_InitialCreate.cs
  LuxStudio/LuxAPI/LuxAPI/Migrations/AppDbContextModelSnapshot.cs
  LuxStudio/LuxAPI/LuxAPI/Models/Client.cs
  LuxStudio/LuxAPI/LuxAPI/Program.cs
  LuxStudio/LuxAPI/LuxAPI/appsettings.Development.json
  LuxStudio/LuxAPI/README.md
  LuxStudio/portal/index.html
Labels: Feature

#231 merge: Develop to Main
  CHANGELOG.md
  Modules/LuxFilter/.gitattributes
Labels: released on @develop

#234 fix: Correct SSO authorization URL to use frontend URL
  .github/workflows/build-upload-lda.yml
  .github/workflows/build-upload-standard-modules.yml
  .github/workflows/sonar-analysis.yml
  CHANGELOG.md
  LuxStudio/LuxAPI/LuxAPI/Controllers/DesktopController.cs
  Modules/LuxFilter/.gitignore
  Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPModel/.gitignore
  Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPModel/negative.txt
  Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPModel/onnx_export.py
  Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPModel/positive.txt
  Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPModel/requirements.txt
Labels: Bug

#240 merge: Develop to Main
  .circleci/config.yml
  CHANGELOG.md
  LuxStudio/depl/overlays/pluto/ingress.yaml
  LuxStudio/depl/overlays/pluto/kustomization.yaml
  LuxStudio/depl/overlays/pluto/patch-deployment-luxapi.yaml
  LuxStudio/depl/overlays/pluto/patch-deployment-luxstudio.yaml
Labels: Feature
