Repository LuxoriaSoft/Luxoria, pull requests merged in 2025-09, with the labels that each got.

#391 feat: Fix names of modules in navigation bar
  Modules/LuxEditor/LuxEditor/LuxEditor.cs
  Modules/LuxExport/LuxExport/LuxExport.cs
  Modules/LuxStudio/LuxStudio/LuxStudio.cs
Labels: Feature

#393 fix: Upload exe before zipping the remaining part
  .github/workflows/release-artifacts.yml
Labels: Bug

#399 Feat/lda/luxexport
  Modules/LuxExport/LuxExport/Components/Export.xaml
  Modules/LuxExport/LuxExport/Components/Export.xaml.cs
  Modules/LuxExport/LuxExport/Components/ExportProgressWindow.xaml.cs
  Modules/LuxExport/LuxExport/Logic/ExportPresetService.cs
  Modules/LuxExport/LuxExport/Logic/ExportViewModel.cs
  Modules/LuxExport/LuxExport/Logic/Exporters.cs
  Modules/LuxExport/LuxExport/Logic/FileSizeOptimizer.cs
  Modules/LuxExport/LuxExport/Models/ExportPreset.cs
Labels: Feature

#400 feat: Change LuxImport brochure on Luxoria Marketplace
  .github/workflows/marketplace-upload.yml
  Modules/LuxImport/docs/README.md
  Modules/LuxImport/docs/luximport.mainview.png
  Modules/LuxImport/luxmod.json
  tools/luxmktplacemgr/src/uploadmgr/main.py
Labels: Documentation

#407 fix: Specify TypeInfoResolver (fixing crashes on x86)
  Modules/LuxExport/LuxExport/Logic/ExportPresetService.cs
  Modules/LuxExport/LuxExport/Logic/ExportViewModel.cs
Labels: Bug

#419 fix: Sliders not sliding smoothly in Layers
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/LayersDetailsPanel.cs
Labels: Bug

#439 feat: Bring Saturn Deployment In
  .circleci/config.yml
  LuxStudio/depl/overlays/saturn/configmap-luxdb-init.yaml
  LuxStudio/depl/overlays/saturn/ingress.yaml
  LuxStudio/depl/overlays/saturn/kustomization.yaml
  LuxStudio/depl/overlays/saturn/luxapi-secrets.sh
  LuxStudio/depl/overlays/saturn/namespace.yaml
  LuxStudio/depl/overlays/saturn/patch-deployment-luxapi.yaml
  LuxStudio/depl/overlays/saturn/patch-deployment-luxstudio.yaml
  LuxStudio/depl/saturn/deployment.yaml
  LuxStudio/depl/saturn/ingress.yaml
  LuxStudio/depl/saturn/service.yaml
Labels: Feature

#459 Feat/lda/luxeditor
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/CropController.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ParametricCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/PointCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ThresholdBar.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/Brush.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/LinearGradient.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/RadialGradient.cs
  Modules/LuxEditor/LuxEditor/Logic/CropProcessor.cs
  Modules/LuxEditor/LuxEditor/Utils/DpiCanvas.cs
  Modules/LuxEditor/LuxEditor/Utils/DpiHelper.cs
Labels: Bug

#466 Develop to Main
  .github/workflows/build-upload-lda.yml
  CHANGELOG.md
  Luxoria.App/Luxoria.App/Components/MainMenuBarComponent.xaml.cs
  Luxoria.App/Luxoria.App/Luxoria.App.csproj
  Luxoria.App/Luxoria.App/Views/MarketplaceView.xaml.cs
  Luxoria.App/Luxoria.Core.Tests/VaultAndStorageTests.cs
  Luxoria.App/Luxoria.Core/Interfaces/IStorageAPI.cs
  Luxoria.App/Luxoria.Core/Interfaces/IVaultService.cs
  Luxoria.App/Luxoria.Core/Luxoria.Core.csproj
  Luxoria.App/Luxoria.Core/Services/VaultService.cs
  Luxoria.App/Luxoria.Modules/Interfaces/IStorageAPI.cs
  Luxoria.App/Luxoria.Modules/Luxoria.Modules.csproj
  Luxoria.App/Luxoria.Modules/Services/StorageAPI.cs
  Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/CropController.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ParametricCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/PointCurve.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ThresholdBar.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/Brush.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/LinearGradient.cs
  Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolControls/RadialGradient.cs
  Modules/LuxEditor/LuxEditor/Logic/CropProcessor.cs
  Modules/LuxEditor/LuxEditor/Utils/DpiCanvas.cs
  Modules/LuxEditor/LuxEditor/Utils/DpiHelper.cs
  Modules/LuxImport/LuxImport/Views/IndexicationView.xaml.cs
Labels: Bug
